### ISSUE TITLE
Code runs very slow on GPU

### ISSUE THREAD

**Issue by umamahesh999** [yuvalpinter/Mimick#12]
I ran a mimick algorithm on a small data set and it is taking 5 mins on CPU. But when I run the same on GPU it is taking 40 mins to finish one epoch. Is there a way to fix this?

Can we increase the batch size of this?

**Comment by yuvalpinter** [comment]
Hi,

This code has never been run on GPU, at least not by me. I would deeply
appreciate it if you make the adjustments necessary (dynet's documentation
can help there) and let me know if there's any further issues.
Likewise, there is no batch size implemented in the code as is. The latest
release of dynet does offer support for autobatching:
http://dynet.readthedocs.io/en/latest/tutorials_notebooks/Autobatching.html

- Yuval

**Comment by umamahesh999** [comment]
Thank you so much for the quick reply. I will go through the dynet docs and implement the batching.

**Comment by umamahesh999** [comment]
Could you please explain the predict_emb function. I am not so familiar with rnns and dynet, having a hard time understanding this.

Especially last two lines I am not getting. If you can spare 5 to 10 minutes it would be great. 

    def predict_emb(self, chars):
        dy.renew_cg()

        finit = self.char_fwd_lstm.initial_state()
        binit = self.char_bwd_lstm.initial_state()

        H = dy.parameter(self.lstm_to_rep_params)
        Hb = dy.parameter(self.lstm_to_rep_bias)
        O = dy.parameter(self.mlp_out)
        Ob = dy.parameter(self.mlp_out_bias)

        pad_char = self.c2i[PADDING_CHAR]
        char_ids = [pad_char] + chars + [pad_char]
        embeddings = [self.char_lookup[cid] for cid in char_ids]

        bi_fwd_out = finit.transduce(embeddings)
        bi_bwd_out = binit.transduce(reversed(embeddings))

        rep = dy.concatenate([bi_fwd_out[-1], bi_bwd_out[-1]])

        return O * dy.tanh(H * rep + Hb) + Ob

**Comment by yuvalpinter** [comment]
This is the core of Mimick, basically the implementation of the diagram from the paper. The first three lines initialize the state of the computation graph for a new training/test instance. The next four populate variables from the MLP weight parameters. The next three handle the input, the next two run the BiLSTM on it.
The `rep` line collects the final states of each BiLSTM as the final representation from the character level. The `return` line applies the MLP variables on that representation to obtain the final predicted vector.

**Comment by umamahesh999** [comment]
Thanks for the great intuition.
