### ISSUE TITLE
Compatibility with Python 3

### ISSUE THREAD

**Issue by a3lem** [yuvalpinter/Mimick#13]
Finally got round to experimenting with Mimick only to discover that it targets Python 2 only. (*Insert rant that Python 3 is already a decade old.*) Do you by any chance plan to add support for Python 3?

Thanks!

**Comment by yuvalpinter** [comment]
Amusingly enough, this issue is also a blocker for me on followup projects. Yes, this is planned and now that you've submitted this I'll have more incentive to do so. So thanks :)

**Comment by a3lem** [comment]
That's great to hear! :)
