### ISSUE TITLE
in_vocab count is set to zero

### ISSUE THREAD

**Issue by muralibalusu12** [yuvalpinter/Mimick#5]
The variable `in_vocab` is set to zero on line num. 80 in the `make_dataset.py` file. As a result, when there are oov words in the vocab file, the `words in training count` is always zero in the output.

**Comment by yuvalpinter** [comment]
Yep, thanks for noting this. [here](https://github.com/yuvalpinter/Mimick/blob/6cdf303c5a60b26aec12e18bf1d8d96831540c43/mimick/make_dataset.py)'s the original version of the file, where the "test set" was written all at once and `in_vocab` would be incremented as it is written. The initialization is unnecessary.

Do you want to remove it and see if things behave as expected, then submit a PR? You can also change "test" to "inference" if you want, as we're not really evaluating those instances later.

**Comment by muralibalusu12** [comment]
Yep. Done! [Here is the pull request.](https://github.com/yuvalpinter/Mimick/pull/6)
